# Generated by Django 3.2.6 on 2021-08-28 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseModel',
        ),
    ]
