# Generated by Django 3.1.4 on 2021-09-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0004_auto_20210922_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
