# Generated by Django 3.1.4 on 2021-09-15 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0004_keywords'),
    ]

    operations = [
        migrations.DeleteModel(
            name='keywords',
        ),
    ]
