# Generated by Django 3.1.4 on 2021-09-23 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0005_auto_20210923_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdata',
            old_name='rebrics',
            new_name='rubrics',
        ),
    ]
