# Generated by Django 3.1.4 on 2021-09-23 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0006_auto_20210923_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdata',
            old_name='remidies',
            new_name='remedies',
        ),
    ]
