# Generated by Django 3.1.4 on 2021-09-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0007_auto_20210923_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdata',
            name='feedback',
            field=models.BooleanField(default=0),
        ),
    ]
