# Generated by Django 3.2 on 2021-09-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0008_patientdata_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdata',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='patientdata',
            name='rubrics',
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
