# Generated by Django 3.2 on 2021-09-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0009_auto_20210926_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdata',
            name='feedback',
            field=models.BooleanField(default=0),
        ),
    ]
