# Generated by Django 3.2 on 2021-10-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0013_auto_20210930_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='userDocData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uderCID', models.CharField(default='non', max_length=100, unique=True)),
                ('userDID', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='patientdata',
            name='uderCID',
            field=models.CharField(default='non', max_length=100),
        ),
        migrations.AddField(
            model_name='updatedweights',
            name='uderCID',
            field=models.CharField(default='non', max_length=100),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='updatedweights',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
