# Generated by Django 3.2 on 2021-10-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0014_auto_20211027_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='uderCID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='updatedweights',
            name='uderCID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userdocdata',
            name='uderCID',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
