# Generated by Django 3.2 on 2021-10-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0015_auto_20211027_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdocdata',
            name='uderCID',
            field=models.CharField(max_length=100),
        ),
    ]
