# Generated by Django 3.2 on 2021-10-27 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0016_alter_userdocdata_udercid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdata',
            old_name='uderCID',
            new_name='userCID',
        ),
        migrations.RenameField(
            model_name='updatedweights',
            old_name='uderCID',
            new_name='userCID',
        ),
        migrations.RenameField(
            model_name='userdocdata',
            old_name='uderCID',
            new_name='userCID',
        ),
    ]
