# Generated by Django 3.2 on 2021-10-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0017_auto_20211027_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='userCID',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='updatedweights',
            name='userCID',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userdocdata',
            name='userCID',
            field=models.CharField(max_length=200),
        ),
    ]
