# Generated by Django 3.2 on 2021-10-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0018_auto_20211027_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdata',
            name='userCID',
        ),
        migrations.RemoveField(
            model_name='updatedweights',
            name='userCID',
        ),
        migrations.AddField(
            model_name='patientdata',
            name='userDID',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='updatedweights',
            name='userDID',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
