# Generated by Django 3.2 on 2021-11-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0019_auto_20211028_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdata',
            name='age',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='gender',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='updatedweights',
            name='age',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='updatedweights',
            name='gender',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
