# Generated by Django 3.2 on 2021-11-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0021_auto_20211104_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='patientDate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='patientName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userdocdata',
            name='userName',
            field=models.CharField(max_length=100),
        ),
    ]
