# Generated by Django 3.1.4 on 2022-04-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0023_auto_20220313_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='remidieAndRuubricsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubric', models.CharField(max_length=200)),
                ('remidieID', models.CharField(max_length=100)),
                ('rubricID', models.CharField(max_length=100)),
                ('remidie', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=100)),
                ('timesUsed', models.IntegerField()),
            ],
        ),
    ]
