# Generated by Django 3.1.4 on 2022-05-18 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0026_auto_20220518_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updatedweights',
            name='weightTemp',
        ),
    ]
