# Generated by Django 3.1.4 on 2022-05-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0027_remove_updatedweights_weighttemp'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatedweights',
            name='weightTemp',
            field=models.IntegerField(default=0),
        ),
    ]
