# Generated by Django 3.1.4 on 2022-05-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0028_updatedweights_weighttemp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updatedweights',
            name='weightTemp',
        ),
        migrations.AlterField(
            model_name='updatedweights',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
