# Generated by Django 3.1.4 on 2022-05-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0029_auto_20220518_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatedweights',
            name='weight',
            field=models.IntegerField(max_length=100),
        ),
    ]
