# Generated by Django 3.1.4 on 2022-05-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0030_auto_20220518_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='updated_weights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userDID', models.CharField(max_length=100)),
                ('patientID', models.CharField(max_length=100)),
                ('rubricRemedies', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('weightTemp', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='updatedWeights',
        ),
    ]
