# Generated by Django 3.1.4 on 2022-05-18 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0031_auto_20220518_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updated_weights',
            name='weightTemp',
        ),
    ]
