# Generated by Django 3.1.4 on 2022-05-21 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0032_remove_updated_weights_weighttemp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remidieandruubricsrecord',
            old_name='remidie',
            new_name='remedy',
        ),
    ]
